apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-dev.macromealsapp.com
  namespace: macromeals-api-dev-ns
spec:
  secretName: macromeals-api-dev-tls
  issuerRef:
    name: letsencrypt-prod-issuer
  dnsNames:
    - api-dev.macromealsapp.com
