"""Vector search service using Replicate embeddings and Supabase vector database.

This module provides functionality to search for similar dishes using image embeddings
generated by Replicate's CLIP model and stored in Supabase vector database.
"""

import os
import logging
import numpy as np
from typing import List, Dict, Optional, Any
from supabase import create_client, Client
from app.services.vector_search.embedding_generator import ReplicateEmbeddingGenerator
from app.core.config import settings

logger = logging.getLogger(__name__)


class VectorSearchService:
    """Service for searching similar dishes using vector embeddings."""
    
    def __init__(self, supabase_url: str = None, supabase_key: str = None):
        """Initialize the vector search service.
        
        Args:
            supabase_url: Supabase project URL
            supabase_key: Supabase API key
        """
        self.supabase_url = settings.SUPABASE_URL
        self.supabase_key = settings.SUPABASE_SERVICE_ROLE_KEY
        
        if not self.supabase_url or not self.supabase_key:
            raise ValueError("Supabase URL and key must be provided")
        
        self.client: Client = create_client(self.supabase_url, self.supabase_key)
        self.embedding_generator = ReplicateEmbeddingGenerator()
        
        logger.info("Initialized VectorSearchService with Replicate embeddings")
    
    async def search_similar_dishes(
        self, 
        image_bytes: bytes, 
        similarity_threshold: float = 0.8,
        match_count: int = 3
    ) -> List[Dict[str, Any]]:
        """Search for similar dishes using image similarity.
        
        Args:
            image_bytes: Raw image bytes to search for
            similarity_threshold: Minimum similarity score (0.0 to 1.0)
            match_count: Maximum number of results to return
            
        Returns:
            List of similar dishes with similarity scores
        """
        try:
            # Generate embedding for the query image
            logger.info("Generating embedding for query image using Replicate")
            query_embedding = self.embedding_generator.generate_embedding(image_bytes)
            
            if query_embedding is None:
                logger.error("Failed to generate embedding for query image")
                return []
            
            # Search for similar dishes in vector database
            embedding_list = query_embedding.tolist()
            
            result = self.client.rpc(
                'search_similar_dishes',
                {
                    'query_embedding': embedding_list,
                    'match_threshold': similarity_threshold,
                    'match_count': match_count
                }
            ).execute()
            
            if hasattr(result, 'error') and result.error:
                logger.error(f"Vector search error: {result.error}")
                return []
            
            # Filter results by similarity threshold
            filtered_results = []
            for dish in result.data or []:
                similarity = dish.get('similarity', 0.0)
                if similarity >= similarity_threshold:
                    filtered_results.append(dish)
                    logger.info(f"Found similar dish: {dish.get('dish_name')} (similarity: {similarity:.3f})")
            
            logger.info(f"Found {len(filtered_results)} dishes above threshold {similarity_threshold}")
            return filtered_results
            
        except Exception as e:
            logger.error(f"Error in vector search: {str(e)}")
            return []
    
    async def search_similar_dishes_by_country(
        self,
        image_bytes: bytes,
        country: str,
        similarity_threshold: float = 0.8,
        match_count: int = 3
    ) -> List[Dict[str, Any]]:
        """Search for similar dishes from a specific country.
        
        Args:
            image_bytes: Raw image bytes to search for
            country: Country to filter by
            similarity_threshold: Minimum similarity score
            match_count: Maximum number of results to return
            
        Returns:
            List of similar dishes from the specified country
        """
        try:
            # Generate embedding for the query image
            query_embedding = self.embedding_generator.generate_embedding(image_bytes)
            
            if query_embedding is None:
                logger.error("Failed to generate embedding for query image")
                return []
            
            # Search for similar dishes by country
            embedding_list = query_embedding.tolist()
            
            result = self.client.rpc(
                'search_similar_dishes_by_country',
                {
                    'query_embedding': embedding_list,
                    'target_country': country,
                    'match_threshold': similarity_threshold,
                    'match_count': match_count
                }
            ).execute()
            
            if hasattr(result, 'error') and result.error:
                logger.error(f"Country search error: {result.error}")
                return []
            
            # Filter results by similarity threshold
            filtered_results = []
            for dish in result.data or []:
                similarity = dish.get('similarity', 0.0)
                if similarity >= similarity_threshold:
                    filtered_results.append(dish)
            
            logger.info(f"Found {len(filtered_results)} dishes from {country} above threshold {similarity_threshold}")
            return filtered_results
            
        except Exception as e:
            logger.error(f"Error in country-specific vector search: {str(e)}")
            return []
    
    def get_dish_by_id(self, dish_id: int) -> Optional[Dict[str, Any]]:
        """Get dish details by ID.
        
        Args:
            dish_id: Database ID of the dish
            
        Returns:
            Dish details or None if not found
        """
        try:
            result = self.client.table('dishes').select('*').eq('id', dish_id).execute()
            
            if result.data:
                return result.data[0]
            return None
            
        except Exception as e:
            logger.error(f"Error getting dish by ID {dish_id}: {str(e)}")
            return None
    
    def get_countries_list(self) -> List[str]:
        """Get list of all available countries in the database.
        
        Returns:
            List of country names
        """
        try:
            result = self.client.table('dishes').select('country').execute()
            
            if result.data:
                countries = list(set([dish['country'] for dish in result.data if dish['country']]))
                return sorted(countries)
            return []
            
        except Exception as e:
            logger.error(f"Error getting countries list: {str(e)}")
            return []

vector_search_service = VectorSearchService()