apiVersion: v1
kind: Namespace
metadata:
  name: macromeals-api-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macromeals-api
  namespace: macromeals-api-ns
spec:
  selector:
    matchLabels:
      run: macromeals-api
  replicas: 1
  template:
    metadata:
      labels:
        run: macromeals-api
    spec:  
      containers:
        - name: macromeals-api
          image: 390844748928.dkr.ecr.eu-west-2.amazonaws.com/dev/macromeals-api:latest
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - |
              python app/main.py
          ports:
            - containerPort: 8000
        
        - name: redis
          image: redis:8.0-M04-alpine3.21
          ports:
            - containerPort: 6379

        - name: worker
          image: 390844748928.dkr.ecr.eu-west-2.amazonaws.com/dev/macromeals-api:worker-latest
          command: ["celery", "-A", "app.worker", "worker", "--loglevel=info"]
          env:
            - name: CELERY_BROKER_URL
              value: "redis://localhost:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://localhost:6379/0"


---
apiVersion: v1
kind: Service
metadata:
  name: macromeals-api-service
  namespace: macromeals-api-ns
spec:
  type: ClusterIP
  selector:
    run: macromeals-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000